### ISSUE TITLE
新增活動：MOPCON 2016

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#10]
``` yml
title: 'MOPCON 2016'
start: '2016-10-29T09:00'
end: '2016-10-30T17:00'
location: '高雄國際會議中心 ( ICCK ) / 高雄市鹽埕區中正四路274號 / 高雄市鹽埕區中正四路274號'
url: 'http://mopcon.org/'
info: |
  本屆議程重心除行動開發技術、服務營運、數位內容三大主軸之外，將更廣泛涵蓋雲端運算、穿戴應用、VR 虛擬實境、AR 擴增實境、物聯網應用與基於 HTML5 的可攜式跨裝置應用等相關議題，以真實運作的案例，向與會者做第一手的探討與分享，促進更多優秀開發者項目的成熟與發展。
org:
  name: 'Mobile Open Platform Conference(MOPCON)'
  url: 'http://mopcon.org/'
```
