### ISSUE TITLE
Happy CSSer - 17

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#100]
```yml
title: 'Happy CSSer - 17'
start: '2017-08-26T13:30'
end: '2017-08-26T17:00'
location: 'T,mot 集界科技 / 台北市大安區羅斯福路三段283巷21弄3號 / 永樂座的「對面」'
url: 'https://www.facebook.com/events/111463029555635/'
info: '出門玩 CSS、嘴一嘴~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
