### ISSUE TITLE
Web前端的切版、動畫特效相關疑難雜症#0

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#101]
```yml
title: 'Web前端的切版、動畫特效相關疑難雜症#0'
start: '2017-08-25T19:30'
end: '2017-08-25T21:00'
location: '好想工作室 / 永康區大武街34號2樓, Tainan, Taiwan 710'
url: 'https://www.facebook.com/events/1991209274446343/'
info: |
  星期五，停水之夜!! 我們來前端聚會吧！

  歡迎帶朋友一起來聚會唷!!

  活動形式:
  請參與者帶「經驗、bug、疑問」來聊聊天吧!!!

  由於希望可以長期進行，所以也是會討論未來進行方式之類的

org:
  name: 'HPX台南讀書會'
  url: 'https://www.facebook.com/hpxtainan/'
```
