### ISSUE TITLE
JSDC 2017 Workshop #1 - 進階 React & Redux

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#102]
```yml
title: 'JSDC 2017 Workshop #1 - 進階 React & Redux'
start: '2017-09-23T10:00'
end: '2017-09-23T17:00'
location: 'UPlace / 台灣台北市大同區長安西路45-1號'
url: 'https://www.facebook.com/events/199539800584897/'
info: |
  KKTIX: https://jsdc-tw.kktix.cc/events/jsdc2017-workshop-part1

  本次課程的目標是讓大家確實的理解 React 相關技術的重要核心概念，並學習一些稍微進階的技巧與架構。適合已經有初步接觸過 React，但希望能鞏固基礎概念並進一步學習進階技巧的開發者。

  React 與 Redux 近年來逐漸成為前端領域最熱門的應用開發解決方案，是前端工程師不可不了解的技術。然而 React 與 Redux 比起傳統如使用 jQuery 等義大利麵疊加式的應用程式，在開發的模式上有很大的不同，因此造就許多初學者容易無法透徹地理解其概念與思想，難以更進一步窺探這個龐大生態系其中的奧秘。

org:
  name: 'JSDC.tw'
  url: 'http://jsdc.tw/'
```
