### ISSUE TITLE
Happy CSSer - 18

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#103]
```yml
title: 'Happy CSSer - 18'
start: '2017-09-09T13:00'
end: ''2017-09-09T17:00''
location: '摩茲工寮 Mozilla Community Space Taipei / 八德路一段94號3F, Taipei, Taiwan 100'
url: 'https://www.facebook.com/events/117454172309133/'
info: '出門玩 CSS、嘴一嘴~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
