### ISSUE TITLE
高雄前端社群#30 - 你的網頁排版有 freestyle 嗎？

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#104]
```yml
title: '高雄前端社群#30 - 你的網頁排版有 freestyle 嗎？'
start: '2017-10-15T09:00'
end: '2017-10-15T12:00'
location: '高雄市鹽埕區七賢三路123號3樓 / 高雄數位內容創意中心'
url: https://www.facebook.com/events/847886185388493/
info: |
  KKTIX: https://gonsakon-7655f2.kktix.cc/events/a5791ac5-f60f9c-cc9dec-eb381d-6b57e9-3a5710-61e623-17b85b-3ac7a7-8f8c6c-3a422e-e7994a-15adf0-335891-740709

  時程表
  14:00~14:10 進場
  14:10~14:30 社群介紹
  14:30~15:30 web layout 的前世今生 (洧杰)
  15:50~16:30 Bootstrap 2~4 演化史 (志誠)

org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390'
```
