### ISSUE TITLE
F2E & RGBA 設計 Meetup 九月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#105]
```yml
title: 'F2E & RGBA 設計 Meetup 九月號'
start: '2017-09-21T19:00'
end: '2017-09-21T22:00'
location: 'Tmot Food / 羅斯福路三段283巷21弄3號, Taipei, Taiwan 大安區'
url: https://www.facebook.com/events/1967303136815878/
info: |
  KKTIX: https://f2e.kktix.cc/events/f2e6-56d17c-0f9e5b-3997b7-a9203f-d684fd-886f38-165143-44d76a-82ae6b-copy-1

  主題： 爛 code 在經過長時間的演化之後，就會變成穩定的爛 code

  這一次我們邀請到 PureScript 的佈道者 CT Wu 分享如何用 Recompose 重構 React Component 及 2017 iT 邦幫忙鐵人賽冠軍 Jerry Hong 分享如何 「畫圖」 寫測試。

org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
