### ISSUE TITLE
JavaScript Ninja #3

### ISSUE THREAD

**Issue by nereuseng** [f2etw/seek-meetup#106]
```yml
# 活動標題
title: 'JavaScript Ninja #3'

# 活動起迄時間，GMT+8，e.q. '2016-07-28T19:30'
start: '2018-01-26T19:30'
end: '2018-01-26T22:00'

# 活動地點
location: 'Smiley Bits 大安區忠孝東路三段88號2樓之2'

# 活動網址
url: 'https://www.meetup.com/BetterDesign/events/246234339/'

# 活動簡介，可選填，可分行
info: '
• What is this
JavaScript Ninja is a programming meetup centered around JavaScript, the most popular programming language according to many sources. We will use the book, Secretes of JavaScript Ninja (2th Edition), as a blueprint to guide us in the way of becoming a real JavaScript Ninja. Based on topics mentioned in the book, we will discuss own discoveries and points learned by sharing code experiment and hands-on project. The point is to make progress, ask questions, and grow stronger as a JavaScript programmer.

• What to do
- 7:30 pm to 7:40 pm : Greeting
- 7:40 pm to 8:00 pm : Discussion (Peers will share what they learn, what they build, or what difficulties they encounter)
- 8:00 pm to 10:00 pm: Group Project (Functions / Layouts / Data Attributes)

• What to bring
- A beginner mind
- A hacker spirit
- A sense of fun'

# 主辦單位資訊，主辦單位資訊子欄位可自行增添
org:
  name: ''
  url: ''

# 是否固定舉辦？以下語法表示每周舉辦一次
repeating:
  freq: 'WEEKLY'
  interval: 2

# 其餘需求若上面沒有，歡迎參考 [ical-toolkit](https://github.com/kushal-likhi/node-ical-toolkit#demo-code-shows-all) 的範例
# 並於 [issue](https://github.com/f2etw/seek-meetup/issues) 或 [giiter](https://gitter.im/f2etw/seek-meetup) 上討論
```
