### ISSUE TITLE
新增活動：F2E&RGBA 設計 Meetup 八月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#11]
``` yml
title: 'F2E&RGBA 設計 Meetup 八月號'
start: '2016-08-26T19:00'
end: '2016-08-26T22:30'
location: 'iCHEF 交誼廳 / 台北市信義區松山路132號3樓'
url: 'http://f2e.kktix.cc/events/f2e6-56d17c-0f9e5b'
info: |
  Keynote 講者：
  * Mooon / 子龍: 「社群conf的設計大亂鬥」
  分享設計g0v 2016 summit的過程，從主視覺到網站與後續的各種不可控制超展開，設計面臨半民主化的一個有痛分娩。開放設計授權與後續回饋經驗談。

  * Estelle: 「Be less busy and more effective.」
  分享嘗試某些方法去修正作業流程；提高工作品質，要回自己的生活。希望大家可以一起成為高效率設計師，遠離無止境的瞎忙！

  * ginger: 「設計師的生存之道」
  要如何報價才不會破壞行情？如何估算成本和市場價值？如何控制業主的要求，讓預算人力不會超支？設計師的生存之道秘訣大公開，一起突破又窮又累的苦境吧！

org:
  name: 'F2ETW'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
