### ISSUE TITLE
新增活動：2016 暑期宅學營

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#12]
``` yml
title: '2016 暑期宅學營'
start: '2016-08-30T09:00'
end: '2016-09-01T16:30'
location: '新北市新莊區中正路510號 輔仁大學聖言樓SF648'
url: 'http://wecolab.kktix.cc/events/weco-f16'
info: |
  期盼已久的暑假終於到來，這個暑假你想好要去旅遊、打工還是自我進修了嗎?
  輔大 WECO LAB 暑期宅學營將帶領你瞭解科技的最新趨勢！讓你就是比別人厲害!
org:
  name: 'WecoLab'
  url: 'http://sls.weco.net/'
```
