### ISSUE TITLE
新增活動：高雄前端社群#25 - 前端與 UI 真心合作的不二法門

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#13]
``` yml
title: '高雄前端社群#25 - 前端與 UI 真心合作的不二法門'
start: '2016-08-28T14:00'
end: '2016-08-28T17:00'
location: '高雄數位內容創意中心 / 高雄市鹽埕區七賢三路123號3樓'
url: 'http://gonsakon-7655f2.kktix.cc/events/a5791ac5-f60f9c-cc9dec-eb381d-6b57e9-3a5710-61e623-17b85b-3ac7a7-8f8c6c'
info: |
  高雄前端社群年度熱門主題：前端與 UI 真心合作的不二法門，就在 8/28 熱烈展開。除了專業的 UI 設計分享設計流程外，我們特別請到 "六位" 相關領域的專家現場即時問答 !!!!  
  活動是在高雄的數創中心，如果你正在世界的其他角落參與偉大的專案而不便前來，這次還提供了現場直播，讓在各地奮鬥的設計師、工程師都能夠一同參與這盛大的問答會。
  * 張瓊文 - UI 設計師分享與工程師合作心法
  * Coffee Talk  -  現場即時問答( 3 位 F2E、3 位 UI )
  * Lighting Talk - PJCHENder 網頁前端資源站

org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390/'
```
