### ISSUE TITLE
新增活動：台中前端社群 08/18 定期聚會 @夢種子

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#14]
``` yml
title: '台中前端社群 08/18 定期聚會 @夢種子'
start: '2016-08-18T19:15'
end: '2016-08-18T21:15'
location: 'Dreamseeds 夢種子 / 西屯區河南路二段262號14F'
url: 'http://taichung-frontend.kktix.cc/events/160818'
info: |
  React Native Action
  本次活動的分享者Tomas Lin透過多年Web開發經驗，將網址切換畫面的概念帶到React Native，也利用網址可攜帶參數的方式管理state，讓React Native畫面的切換更順手。
org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/'
```
