### ISSUE TITLE
新增活動：前端東（React）西（Vue）軍，今晚要點哪一道？

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#18]
``` yml
title: '前端東（React）西（Vue）軍，今晚要點哪一道？'
start: '2016-09-20T19:00'
end: '2016-09-20T22:00'
location: '台北市大同區長安西路 150 號 11 樓之 1 (五倍紅寶石出礦坑)'
url: 'http://www.accupass.com/event/register/1609010719207252286050'
info: |
  Vue.js 和 React.js 是近年火紅的兩大 Javascript 前端渲染方案，本次活動為座談會，由五倍紅寶石邀請了兩位講師一起分享與對談關於使用這兩種方案的經驗。
  * 蘇泰安 (Taian Su)
  * 許國政 (Kuro Hsu)
  * Anna Su

  活動流程：
    18:30 ~ 19:00 入場
    19:00 ~ 20:00 講者發表
    20:00 ~ 20:20 中場休息
    20:20 ~ 21:30 對談 與 QA 時間
org:
  name: '五倍紅寶石'
  url: 'https://5xruby.tw/'
```
