### ISSUE TITLE
新增活動：JSDC 2016

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#2]
``` yml
title: 'JSDC 2016'
start: '2016-10-22T09:00'
end: '2016-10-23T17:00'
location: '中央研究院 人文社會科學館'
url: 'http://2016.jsdc.tw/'
info: 'JSDC (JavaScript Developer Conference) 是台灣最⼤的 JavaScript 年度性技術研討會,旨在提供台灣中⾼階 JavaScript 技術人才與世界最新 JavaScript 相關技術討論與分享。並希望各界廠商合作與中高階技術⼈才的媒合,創造雙贏的正向循環。'
org:
  name: 'JSDC'
  url: 'http://jsdc.tw/'
```
