### ISSUE TITLE
新增活動：Study4.TW -Sep-2016

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#20]
``` yml
title: 'Study4.TW -Sep-2016'
start: '2016-09-24T13:30'
end: '2016-09-24T16:30'
location: '逢甲大學資電館2F(資電248) / 台中市西屯區文華路100號資訊電機館2F(資電248)'
url: 'http://study4-tw.kktix.cc/events/sep-2016-taichung-13145b'
info: |
  * Vue.js 基礎入門 by Kuro Hsu
  * Codeception.js 前端測試入門 by Caesar Chi
org:
  name: 'Study4.TW'
  url: 'http://study4.tw/'
```
