### ISSUE TITLE
新增活動：台灣 AngularJS 社群小聚

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#22]
```yml
title: '台灣 AngularJS 社群小聚'
start: '2016-09-27T18:30'
end: '2016-09-27T21:30'
location: '台北市信義區忠孝東路五段68號19樓 (台灣微軟新辦公室)'
url: 'http://www.accupass.com/go/angularjstw0927'
info: |
  * Angular 2 表單應用 Template-Driven V.S. Model-Driven 大評比?! / Jeff
  * 一次搞懂 RxJS 與 Observable / Kevin Yang
  * 使用 Angular 2 Router 快速建構 SPA 網站 / Will 保哥
org:
  name: '多奇數位創意有限公司'
  url: 'http://www.miniasp.com/'
```
