### ISSUE TITLE
新增活動：ReactNative 仰望星空工作坊 Run3

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#23]
```yml
title: 'ReactNative 仰望星空工作坊 Run3'
start: '2016-10-06T18:30'
end: '2016-10-06T21:00'
location: '台北市中正區八德路一段94號3F / MozTW 摩茲工寮'
url: 'http://f2e.kktix.cc/events/1894833b-e4cec3-f20b42'
info: |
  React Native 是一個使用 React 框架來開發 App 的開源專案，目前已有36k多個 Star 以及7k多個 Commits，希望透過分享讓大家更容易上手 ReactNative，更希望大家可以成為ReactNative的貢獻者之一。
  講者網路ID：YuTin
  本次主題：https://hackpad.com/ReactNative-Run-3-FCvacBYkAxP
  工作坊內容基於 https://github.com/g0v/react-native-sample
  工作坊沒有簡報但有大綱，所以邊分享邊紀錄，然後歡迎大家一起共筆，也可以把分享的內容PR到 專案 的 README.md 或 wiki。
org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
