### ISSUE TITLE
新增活動：F2E&RGBA 設計 Meetup 十月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#24]
```yml
title: 'F2E&RGBA 設計 Meetup 十月號'
start: '2016-10-26T19:00'
end: '2016-10-26T22:00'
location: '台北市信義區松山路132號3樓 / iCHEF 交誼廳'
url: 'http://f2e.kktix.cc/events/f2e6-56d17c-0f9e5b-3997b7-a9203f'
info: |
  * 如何做好使用者訪談 / Hans (台灣使用者經驗設計協會 UiGathering理事)
  * 你要解開心的人是誰？談人物畫像 / Yin peng​
org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
