### ISSUE TITLE
新增活動：Angular 2 新手入門

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#25]
```yml
title: 'Angular 2 新手入門'
start: '2016-11-10T19:15'
end: '2016-11-10T21:15'
location: '西屯區河南路二段262號14F / Dreamseeds 夢種子'
url: 'http://taichung-frontend.kktix.cc/events/161110'
info: |
  當年可以說是橫掃前端js框架的Angular，不但有著母公司Google的大力支持，這次釋出的第二版下挾全球超過百萬個開發者、效能更快與更好上手等特性再次席捲前端而來。本次台中前端社群有幸邀請到林正祥(Tai)來介紹Angular 2的特色以及入門教學，學習如何使用Angular 2打造一流的網站平台，歡迎有興趣的朋友一同進入Angular 2的世界。
org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/permalink/1516690838344837/'
```
