### ISSUE TITLE
新增活動：KKBOX Innovation Chat #14 (高雄場) Frontend 不 end，翻轉辦公室！

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#26]
```yml
title: 'KKBOX Innovation Chat #14 (高雄場) Frontend 不 end，翻轉辦公室！'
start: '2016-11-17T14:00'
end: '2016-11-17T17:00'
location: '高雄市前鎮區復興四路20號A棟1樓 / K Square'
url: 'https://www.facebook.com/events/1701214893529292/'
info: |
  講者及議題介紹：
  * 業餘專案：想像力是你的超能力 / AJ Hsu
  * Bootstrap與他的好搭檔 / Casper
  FB 活動主頁： https://www.facebook.com/events/1701214893529292/

org:
  name: 'KKBOX Innovation Chat'
  url: 'http://innovation.kktix.cc/events/frontend-dev-guide'
```
