### ISSUE TITLE
新增活動：F2E&RGBA 設計 Meetup 十一月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#28]
```yml
title: 'F2E&RGBA 設計 Meetup 十一月號'
start: '2016-11-25T19:00'
end: '2016-11-25T21:00'
location: '台北市中山區復興北路420號15樓 / 巴哈姆特 交誼廳'
url: 'http://f2e.kktix.cc/events/f2e6-56d17c-0f9e5b-3997b7-a9203f-47477d'
info: |
  * 微型互動設計：使用動畫塑造良好體驗 / 胡豫
  * UI Kit 的設計與應用 / Yu-Ru Lee

org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
