### ISSUE TITLE
新增活動：台北前端社群讀書會

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#3]
``` yml
title: '台北前端社群讀書會'
start: '2016-07-13T19:00'
end: '2016-07-13T21:00'
location: '伯朗咖啡科大店(台北市大安區忠孝東路三段52號)'
url: 'https://www.facebook.com/events/1567298413564943/'
info: |
  讀書會形式
  從書單中選出讀書會討論的書，每本書約一至二個月內讀完(每週讀一至二個章節即可)。
  讀書會分為初學與進階兩種組別：
  初學組：適合完全不會或有一些基礎的人
  進階組：適合有實務經驗且想要更進階深入的人
  兩個組別中各挑選一本書，若在閱讀的過程中不了解或不清楚，可以提出與大家一起討論。

org:
  name: '台北前端社群'
  url: 'https://www.facebook.com/groups/f2e.taipei/'

repeating:
  freq: 'WEEKLY'
  interval: 1
```
