### ISSUE TITLE
新增活動：台中前端社群 2016 歲末之戰-餐桌大亂鬥

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#32]
```yml
title: '台中前端社群 2016 歲末之戰-餐桌大亂鬥'
start: '2016-12-16T19:00'
end: '2016-12-16T21:30'
location: '404台中市北區育才北路20號 / 菲淇士義式廚房'
url: 'http://taichung-frontend.kktix.cc/events/161216'
info: |
  12月是感恩與相聚的季節，台中前端社群也要辦個年終大聚餐來應景一下。
  歡迎參加過我們的活動或平時有在關注的好朋友，趁著這個機會一起與我們聊個痛快。

  這次我們將有 "前端工程" 討論桌、"前端設計" 討論桌、"工作苦水" 桌以及 "認識新朋友" 桌。

  大家可以利用這個機會，在享受美食之餘討論技術或者工作上的種種，也可以單純來這裡交個朋友。
  和大家交流的同時要記得帶自己的名片喔。

org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/permalink/1561524923861428/'
```
