### ISSUE TITLE
新增活動：F2E&RGBA 設計 Meetup 十二月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#34]
```yml
title: 'F2E&RGBA 設計 Meetup 十二月號'
start: '2016-12-27T19:00'
end: '2016-12-27T22:00'
location: '台北市信義區松山路132號3樓 / iCHEF 交誼廳'
url: 'http://f2e.kktix.cc/events/f2e6-56d17c-0f9e5b-3997b7-a9203f-d684fd'
info: |
  1.CJ
  講題：Git, let it flow!
  講題簡介: 如何讓多人協作更加輕鬆，版控更加明確。Git flow here you are! 😉
 
  2.夏翔 Kyle Hsia
  講題：Git Git Git 
  講題簡介: 將Git觀念水乳交融地應用在設計師的日常工作中，分享自身的版本控制管理經驗及與工程師的Team work方式
 
  3. Ginger
  講題：進入大平台時代吧！設計師們 - git 版控實況秀
  講題簡介：會實際操作 sketch 和 git 怎麼連結，並且示範套件如何協助版本控制，從此以後存檔不在需要 v1 v2 v3，只需要 commit。
 
org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
