### ISSUE TITLE
新增活動：快樂貓咪設計師 – 天下一預載貓武鬥會

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#35]
```yml
title: '快樂貓咪設計師 – 天下一預載貓武鬥會'
start: '2017-02-10T19:30:00'
end: '2017-02-10T21:30:00'
location: '台灣台北市中正區衡陽路7號5樓 / 五倍紅寶石'
url: 'http://happydesigner.kktix.cc/events/world-loading-cat-championship'
info: |
  每個參賽者有 5 分鐘時間可以說明你的設計。
  評審團：
  * Amos Lee，飛肯設計學苑 CSS 講師
  * Paul Li。Yahoo 前端工程師
org:
  name: '快樂設計師 HappyDesigner'
  url: 'http://happydesigner.kktix.cc/'
```
