### ISSUE TITLE
新增活動：【達暉資訊】August 魔法師小聚來囉 ❗'

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#4]
``` yml
title: '【達暉資訊】August 魔法師小聚來囉 ❗'
start: '2016-08-03T19:30'
end: '2016-08-03T22:00'
location: '達暉資訊 / 台北市信義區基隆路二段189號14樓之10'
url: 'http://lustertech.kktix.cc/events/833a53a7-eb8e88-a1e40a-6d221e'
info: |
  ❤適合參加的對象❤

  - 「曾想過要成為全端工程師」的工程師
  - 「想來聽聽前端經驗甘苦談」的一般人
  - 「想要準備玩前端，又想找人一起玩」的任何人
  - 「跟我一樣正在探索新前端技術」的前端愛好者
  - 「非常熱血，不吝嗇分享及愛與人交流」的前端愛好者

  社團網址
  https://www.facebook.com/groups/1635233983410054/

org:
  name: '前端魔法師'
  url: 'https://www.facebook.com/groups/1635233983410054/'
```
