### ISSUE TITLE
新增活動：台中前端社群 02/25 定期聚會 @夢種子

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#40]
```yml
title: '台中前端社群 02/25 定期聚會 @夢種子'
start: '2017-02-25T14:00:00'
end: '2017-02-25T16:00:00'
location: '台中市西屯區河南路二段262號14F / Dreamseeds 夢種子'
url: 'http://taichung-frontend.kktix.cc/events/170225'
info: |
  HTML5 Canvas 好好玩 (by 翁文鴻 Horken)
  *本次活動適合有 JS 開發經驗的朋友
  這是一場定期主題性聚會，歡迎一起來聊聊！！
  不是上課而是聚會，不論是初學者或是資深人士，期望你能在這聚會教學相長獲得更多。
org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/'
```
