### ISSUE TITLE
新增活動：高雄前端社群#27 - JavaScript 初心者工作坊

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#41]
```yml
title: '高雄前端社群#27 - JavaScript 初心者工作坊'
start: '2017-03-26T09:30:00'
end: '2017-03-26T17:30:00'
location: '高雄市鹽埕區七賢三路123號3樓 / 高雄數位內容創意中心'
url: 'http://gonsakon-7655f2.kktix.cc/events/a5791ac5-f60f9c-cc9dec-eb381d-6b57e9-3a5710-61e623-17b85b-3ac7a7-8f8c6c-3a422e-e7994a'
info: |
  本次 JavaScript 工作坊教材將會使用 JavaScript 30 ，
  一開始將會從 JS 基礎開始介紹，後面便會帶入各章節進行講解，
  只要你有 HTML、CSS 基礎便可很輕易理解本次工作坊授課內容，
  儘管你在外縣市，我們也會提供直播讓大家在線上一同參與哩 :D
  PS：有任何前端與網頁設計問題，歡迎加入六角學院 @line 群組發問
  六角學院 LINE ID：@guv7422g

org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390'
```
