### ISSUE TITLE
新增活動：JavaScript Group / 20170314

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#46]
```yml
title: 'JavaScript Group / 20170314'
start: '2017-03-14T19:00'
end: '2017-03-14T21:30'
location: '10059台北市中正區新生南路一段50號12樓B室 / 威肯金融科技股份有限公司'
url: 'http://javascript-tw.kktix.cc/events/jstw-20170314'
info: '本場講題內，我們會來聊聊所謂的網頁金流（特別是信用卡代收代付）的部分，因為我知道很多工程師第一次碰到金流總是會抖抖的，我自己當初也是。我們將在活動中介紹跟解說，如何界接網站金流！對這個議題「入門」有興趣的，歡迎來一起討論。'
org:
  name: 'JavaScript.tw'
  url: 'http://www.facebook.com/groups/186298388138174/'
```
