### ISSUE TITLE
新增活動：Firebug 開發者 Honza 跟你聊：不斷進化中的 Firefox 開發工具

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#48]
```yml
title: 'Firebug 開發者 Honza 跟你聊：不斷進化中的 Firefox 開發工具'
start: '2017-03-22T19:30'
end: '2017-03-22T21:00'
location: '八德路一段94號3F, Taipei, Taiwan 100 / 摩茲工寮'
url: 'https://moztw.kktix.cc/events/fx-devtool-honza'
info: |
  在這次的分享裡 Firefox DevTools 開發者 Honza 要跟大家聊聊 DevTools 的近況，歡迎對 Firefox 開發工具有興趣的網頁開發者參加。

  關於講者
  Jan "Honza" Odvarko 在 Mozilla 工作。
  他是知名的 Firebug 專案的主要開發者，並且持續致力於改善 Firefox 的內建開發工具。

  講題：About DevTools
  本次內容將為英文
org:
  name: 'Mozilla 台灣社群'
  url: 'https://www.facebook.com/MozTW/'
```
