### ISSUE TITLE
新增活動：Modern Web 2016

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#5]
``` yml
title: 'Modern Web 2016'
start: '2016-08-24T09:00'
end: '2016-08-25T17:00'
location: '台北文創 6F(台北市信義區菸廠路88號 6F)'
url: 'http://modernweb.tw/'
info: |
  技術在我們手上，世界就在我們手上

  * 世界級大師揭示Web發展動態
  * 中國Web/電子商務專家齊聚
  * 台灣業界高手不藏私分享

org:
  name: 'iThome'
  url: 'http://www.ithome.com.tw/'
```
