### ISSUE TITLE
+ 高雄前端開發者大會

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#50]
```yml
title: '高雄前端開發者大會'
start: '2017-05-06T09:00'
end: '2017-05-06T18:00'
location: '807高雄市三民區十全一路100號 / 高雄醫學大學地下二樓'
url: 'http://www.ksf2e.com/'
info: |
  大家好，我們是高雄前端社群，四年多來不斷累積能量，醞釀許久終於有了這次活動，聯手六角學院、好想工作室及各路熱血志工，邀請由南到北、各大前端技術領域大神講師們，探討最新、最狂的前端議題！
  歡迎大家到現場共襄盛舉，無法前來也沒關係，可以在直播上一同參與！
org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390/'
```
