### ISSUE TITLE
+台中前端社群 04/13 定期聚會 @夢種子

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#54]
```yml
title: '台中前端社群 04/13 定期聚會 @夢種子'
start: '2017-04-13T19:10'
end: '2017-04-13T21:10'
location: '西屯區河南路二段262號14F / Dreamseeds 夢種子'
url: 'https://taichung-frontend.kktix.cc/events/170413'
info: |
  完全理解JS的事件觸發與異步處理
  * JS異步處理與事件觸發 介紹
  
org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/'
```
