### ISSUE TITLE
+那些常用的 ES6 features

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#55]
```yml
title: '那些常用的 ES6 features'
start: '2017-05-11T14:00'
end: '2017-05-11T16:00'
location: '台南市永康區大武街34號2樓 (康是美樓上，側邊入口進入)'
url: 'http://www.accupass.com/go/es6features'
info: |
  Javascript 是 Web application 中一個非常重要的語言，而 ECMAScript 6(ES6) 是 Javascript 演化中的一個很重大的改變，因為 ES6 的出現，他改變了很多 js 開發人員的方式與習慣。
  TonyQ 從事網頁開發歷經快十年，js 一直都是他的好夥伴，對於 ES6 這種大的改變，他來介紹那些常用到的 ES6 features。
org:
  name: '好想工作室'
  url: 'https://www.facebook.com/GoodideasStudio/'
```
