### ISSUE TITLE
+FDG Taiwan #1 Meetup - F8 Party!

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#56]
```yml
title: 'FDG Taiwan #1 Meetup - F8 Party!'
start: '2017-04-19T19:00'
end: '2017-04-19T21:30'
location: '105台北市松山區民權東路三段142號17樓, Taipei, Taiwan 105 / CHOCOLABS 歐酷網路'
url: 'https://www.facebook.com/events/1369723676446873/'
info: |
  Facebook 的年度開發者大會 F8 即將於 4/18 - 19 於美國舊金山舉行，而在這個年度盛會上 Facebook 將一如往例介紹新產品，並和大家分享 Facebook 的重要年度發展。
  由於並非大家都能飛去舊金山參加，本社團 (#FDGtw) 將在 4/19 (三) 和各位一起回味今年 Facebook F8 大會所發表的一系列新技術、新產品，歡迎一同來參加交流！
org:
  name: 'Facebook Developer Circle: Taipei'
  url: 'https://www.facebook.com/groups/DevCTaipei/'
```
