### ISSUE TITLE
+A-Frame School Study Group

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#59]
```yml
title: 'A-Frame School Study Group'
start: '2017-05-20T14:00'
end: '2017-05-20T18:00'
location: '台北市中正區八德路一段 94 號 3F / 摩茲工寮 (Mozilla Community Space Taipei)'
url: 'https://moztw.kktix.cc/events/aframe-school'
info: |
  用 A-Frame 踏入 WebVR 的世界，簡單入門動手學！
  * A-Frame School (英文版)
  * A-Frame School (中文緩慢翻譯版, coming soon!)

org:
  name: 'MozTW（Mozilla 台灣社群）'
  url: 'http://moztw.org/'
```
