### ISSUE TITLE
新增活動：COSCUP 2016

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#6]
``` yml
title: 'COSCUP 2016'
start: '2016-08-20T09:00'
end: '2016-08-21T17:00'
location: '中央研究院 活動中心及人文社會科學館'
url: 'http://coscup.org/2016/'
info: |
  “ It’s BETTER when it’s SHARED. ”
  「分享」一直以來都是 COSCUP 的主軸，我們相信，唯有透過分享、討論與眾人的再創造，才能真正落實 open source 的精神與信念，帶給這個世界更多的可能。

org:
  name: 'COSCUP'
  url: 'http://coscup.org/'
```
