### ISSUE TITLE
+Happy CSSer - 9

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#61]
```yml
title: 'Happy CSSer - 9'
start: '2017-05-07T13:30'
end: '2017-05-07T17:30'
location: '八德路一段94號3F, Taipei, Taiwan 100 / 摩茲工寮'
url: 'https://www.facebook.com/events/808946855926054/'
info: '宅宅出門一起寫 CSS Animation～'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
