### ISSUE TITLE
+Happy CSSer - 8

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#62]
```yml
title: 'Happy CSSer - 8'
start: '2017-04-22T13:30'
end: '2017-04-22T18:00'
location: '台北市民權東路二段148號1F / 丹堤咖啡館'
url: 'https://www.facebook.com/events/1539533432726394/'
info: '宅宅出門一起寫 CSS ～'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
