### ISSUE TITLE
+Facebook Developer Circle: Taipei 2017 #1

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#63]
```yml
title: 'Facebook Developer Circle: Taipei 2017 #1'
start: '2017-05-17T19:00'
end: '2017-05-17T22:00'
location: '105台北市松山區民權東路三段142號17樓, Taipei, Taiwan 105 / CHOCOLABS 歐酷網路'
url: 'https://www.facebook.com/events/1457410804279597/'
info: |
  活動場地約可容納 100人 (座位 60 個 + 吧台椅 20 張 + 站位 20
個，所以就算報名成功，仍有部分人須站著參加活動)，為了維持場地的舒適性及有效控制人數，請各位先在活動頁
(https://www.facebook.com/events/1457410804279597) 上按參加，再於 KKTIX (https://fdctaipei.kktix.cc/events/fdc201705) 上完成報名手續，才算報名成功，若沒報到的朋友可以不用擔心，當天也會有直播，讓大家可以遠端參與活動。

  ▼ 講者與主題
  1.【ReactVR】by Jeremy 
  2.【Self-Serve Facebook Ads w/ Marketing API】by Clement (91APP)
  3.【F8 Highlights】by Guannan (Facebook)
  ▼ Lightning talk
  【With react and sketchapp, code a design system.】by Chin, Tagtoo 塔圖科技 前端工程師
org:
  name: 'Facebook Developer Circle: Taipei'
  url: 'https://www.facebook.com/groups/DevCTaipei/'
```
