### ISSUE TITLE
+Happy CSSer - 10

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#64]
```yml
title: 'Happy CSSer - 10'
start: '2017-05-21T13:30'
end: '2017-05-21T17:30'
location: '台北市大安區羅斯福路三段283巷21弄6號 / 永樂座的「對面」'
url: 'https://www.facebook.com/events/1348065795285549/'
info: '出門用嘴巴寫 CSS ~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
