### ISSUE TITLE
+Vue.js 台灣 Meetup - 2017 #01

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#65]
```yml
title: 'Vue.js 台灣 Meetup - 2017 #01'
start: '2017-06-01T19:00'
end: '2017-06-01T22:00'
location: '台北市中正區衡陽路 7 號 5 樓 / 五倍紅寶石'
url: 'https://vuejs.kktix.cc/events/meetup-201701'
info: |
  Talk1:  由 jQuery 轉 VueJS 的正確姿勢 [新手向]
  Talk2:  使用現代前端框架 (如 VueJS) 如何兼顧 SEO [血汗向]
org:
  name: 'Vue.js 台灣'
  url: 'https://www.facebook.com/groups/vuejs.tw/'
```
