### ISSUE TITLE
+WebVR with A-Frame: A-Frame School 自助會

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#67]
```yml
title: 'WebVR with A-Frame: A-Frame School'
start: '2017-06-03T18:00'
end: '2017-06-03T22:00'
location: '台北市中正區八德路一段 94 號 3F / 摩茲工寮 (Mozilla Community Space Taipei)'
url: 'https://www.facebook.com/events/1891077437810030/'
info: |
  KKTIX: https://moztw.kktix.cc/events/aframe-school-170603
  本次您將採用 A-Frame 學院這套自學教材，跟著其中的說明一步步打造 VR 場景。我們也會大概介紹一下 WebVR 的原理跟發展現況，讓網站開發者們都能順利上手。準備好了嗎？帶著筆電前往摩茲工寮，一起進入 WebVR 的世界吧！

org:
  name: 'MozTW（Mozilla 台灣社群）'
  url: 'http://moztw.org/'
```
