### ISSUE TITLE
+Happy CSSer - 11

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#68]
```yml
title: 'Happy CSSer - 11'
start: '2017-06-04T13:30'
end: '2017-06-04T17:30'
location: '台北市大安區羅斯福路三段283巷21弄6號 / 永樂座的「對面」'
url: 'https://www.facebook.com/events/1348065795285549/'
info: '出門玩 CSS、嘴一嘴~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
