### ISSUE TITLE
+台灣 Angular 社群小聚：用企業級的平台在前端世界乘風破浪

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#69]
```yml
title: '台灣 Angular 社群小聚：用企業級的平台在前端世界乘風破浪'
start: ' 2017-06-24T13:00'
end: '2017-06-24T17:00'
location: ' 台北市松山區八德路四段123號3樓 (大船艦 The Flagship - 甲板廣場區)'
url: 'http://www.accupass.com/go/ngtw2017'
info: |
  優異的 Angular 前端框架經過多年的淬鍊發展，已經醞釀出完整的開發生態系，不但擁有豐富的開發工具與外掛，還有大量現成的 UI 元件與函式庫可用，更可整合市面上大量的 jQuery, jQuery UI 或其他 VanillaJS 前端套件，世界上也越來越多以 Angular 完成的作品。這些都是幫助各位在前端世界乘風破浪的關鍵要素。本次我們特別邀請到 7 位講者，用一個下午的時間，釋放你的大腦、打開你的眼界，歡迎 6/24 (六) 跟我們一起.乘.風.破.浪.！

org:
  name: 'Angular User Group Taiwan'
  url: 'https://www.facebook.com/groups/augularjs.tw/'
```
