### ISSUE TITLE
+F2E & RGBA 設計 Meetup 六月號

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#70]
```yml
title: 'F2E & RGBA 設計 Meetup 六月號'
start: '2017-06-22T19:00'
end: '2017-06-22T21:30'
location: '110台北市信義區松山路132號 / ichef'
url: 'https://www.facebook.com/events/669377536587724/'
info: |
  * 設計師的自我修煉之路 / Simon Lin
  * 新創也可以做 user research 嗎？ / Ginger

org:
  name: 'Front-End Developers Taiwan'
  url: 'https://www.facebook.com/groups/f2e.tw/'
```
