### ISSUE TITLE
+Happy CSSer - 12

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#71]
```yml
title: 'Happy CSSer - 12'
start: '2017-06-17T13:00'
end: '2017-06-17T17:30'
location: '台北市大安區羅斯福路三段283巷21弄3號 / 永樂座的「對面」'
url: 'https://www.facebook.com/events/1348065795285549/'
info: '出門玩 CSS、嘴一嘴~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
