### ISSUE TITLE
+Vue.js：前端框架的演進淺談 - iThome Tech Talk系列講座

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#72]
```yml
title: 'Vue.js：前端框架的演進淺談 - iThome Tech Talk系列講座'
start: '2017-07-05T19:20'
end: '2017-07-05T21:30'
location: '台北市信義區忠孝東路五段293號3樓 / BOOKSHOW 說書會'
url: 'http://learning.ithome.com.tw/course/7qPwH4jo83z2'
info: |
  * Kuro Hsu
  雖然長久以來流傳著「每 18 至 24 個月，前端都會難一倍」 的說法，但事實上技術沒有強弱之分，只有適合與否。
  在本次分享中，我將從 Vue.js 出發，與各位談談近年來前端框架的演進與比較。除了鑑古知今了解前端工具發展的趨勢外，同時也將透過簡單的範例來說明，為什麼我會選擇投入 Vue.js 的世界。

org:
  name: 'iThome Tech Talk'
  url: 'http://techtalk.ithome.com.tw/'
```
