### ISSUE TITLE
+台中前端社群 2017 年中聚會-設計師&工程師的交流

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#73]
```yml
title: '台中前端社群 2017 年中聚會-設計師&工程師的交流'
start: '2017-06-24T11:50'
end: '2017-06-24T14:30'
location: '台中市西區華美街410號 / 7分SO美式廚房-華美店'
url: 'https://taichung-frontend.kktix.cc/events/170624'
info: |
  時光飛逝，距離上次餐桌大亂鬥又過了半年，是時候將大家再聚集起來吃吃喝喝、聊聊是非了。
  這次我們將有 "前端工程" 討論桌、"前端設計" 討論桌、"工作苦水" 桌以及 "認識新朋友" 桌。

  大家可以利用這個機會，在享受美食之餘討論技術或者工作上的種種，也可以單純來這裡交個朋友。

  和大家交流的同時要記得帶自己的名片喔。

org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/'
```
