### ISSUE TITLE
+高雄前端社群#28 - WebVR A-Frame workshop

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#76]
```yml
title: '高雄前端社群#28 - WebVR A-Frame workshop'
start: '2017-07-01T14:00'
end: '2017-07-01T17:00'
location: '高雄市鹽埕區七賢三路123號3樓 / 高雄數位內容創意中心'
url: 'https://gonsakon-7655f2.kktix.cc/events/a5791ac5-f60f9c-cc9dec-eb381d-6b57e9-3a5710-61e623-17b85b-3ac7a7-8f8c6c-3a422e-e7994a-15adf0'
info: |
  WebVR A-Frame workshop

org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390/'
```
