### ISSUE TITLE
+AsiaYo MeetUp #5 90天橫掃亞洲住宿關鍵字的seo獨門心法 - AsiaYo 實作秘辛大揭露

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#77]
```yml
title: 'AsiaYo MeetUp #5 90天橫掃亞洲住宿關鍵字的seo獨門心法 - AsiaYo 實作秘辛大揭露'
start: '2017-06-28T19:15'
end: '2017-06-28T21:30'
url: 'https://www.facebook.com/events/1860218774299141/'
location: '台北市敦化南路二段77號18樓之3 / AsiaYo 台北辦公室'
info: |
  Lucas Hsieh, 現為 AsiaYo Product Lead, 將與大家分享 AsiaYo 是如何系統性的執行 SEO 專案，橫掃台灣、日本、韓國、泰國主要城市的住宿、旅遊關鍵字排名，並勝過多數知名國際訂房網。坊間 SEO 說法百百種，碰到實際的狀況該如何解決？踩到雷時又該怎麼辦？歡迎大家來與我們一起交流如何找對關鍵字，做好 SEO, 在短短 90 天內橫掃亞洲住宿關鍵字，讓AsiaYo被看見！

org:
  name: 'AsiaYo MeetUp'
  url: 'https://www.facebook.com/groups/1101133463337016/'
```
