### ISSUE TITLE
+MOPCON 2017

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#78]
```yml
title: 'MOPCON 2017'
start: '2017-10-28T08:30'
end: '2017-10-29T18:00'
location: '高雄國際會議中心 ( ICCK ) / 高雄市鹽埕區中正四路274號'
url: 'http://mopcon.org/'
info: 'MOPCON 2017 行動科技年會'
org:
  name: 'MOPCON'
  url: 'http://mopcon.org'
```
