### ISSUE TITLE
+ ModernWeb 2017

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#79]
```yml
title: 'ModernWeb 2017'
start: '2017-08-10T09:00'
end: '2017-08-11T17:00'
location: '臺灣大學社會科學院 / 臺北市大安區羅斯福路四段一號'
url: 'http://modernweb.tw/'
info: 'Modern Web 2017 技術在我們手上，世界就在我們手上'
org:
  name: 'iThome'
  url: 'http://www.ithome.com.tw/'
```
