### ISSUE TITLE
新增活動：2016台電開放資料暖身黑客松

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#8]
``` yml
title: '2016台電開放資料暖身黑客松'
start: '2016-08-07T08:30'
end: '2016-08-07T20:30'
location: '台電大樓副樓11樓 / 臺北市羅斯福路三段242號副樓11樓'
url: 'http://optphkt.kktix.cc/events/tpodwarmupthon'
info: |
  電力是現代化社會的基石，也是經濟發展的動力，是生活中不可或缺的必需品，台電開放資料黑客松以全民為本，透過黑客松的競賽精神，邀請參賽者透過短時間的密集思考，一起攜手邁向「創意大未來」，除進一步具體實踐台電不變的開放理念，更希望透過參賽者的創意與專業，讓社會瞭解與共同正視電力供需現況。
  https://docs.google.com/document/d/1PZNPSBbk1jSwHCp22ZxLmSHFFezfX1wYg-BqD7DqUvQ/edit
org:
  name: '台灣電力公司'
  url: 'http://www.taipower.com.tw/'
  email: 'OPENTPTEAM@gmail.com'
```
