### ISSUE TITLE
+ Chrome Extension: 每個網頁都是你的遊樂場

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#80]
```yml
title: 'Chrome Extension: 每個網頁都是你的遊樂場'
start: '2017-06-29T19:00'
end: '2017-06-29T20:30'
location: '臺灣文創訓練中心-台中文創館 ​0305​場地 / 台中市西區台灣大道二段2號 3F-3'
url: 'https://www.facebook.com/trunk.studio.tw/posts/871827932971495'
info: |
  kktix: https://trunk-studio.kktix.cc/events/20170511-apixsideproject-132843-132c72

  聽說 Chrome、Firefox 都有 Extension，我們經常使用，但是卻不太清楚它能做到什麼？

  它不僅可以操作所有網頁，為它們增加功能，也可以做成獨立的應用程式，例如著名的 adblock -- 一款人人皆知的廣告阻擋器，在這次活動我將帶領各位踏入 Chrome Extension 的世界。

org:
  name: 'Trunk Studio 創科資訊'
  url: 'https://www.facebook.com/trunk.studio.tw/'
```
