### ISSUE TITLE
+ COSCUP 2017

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#81]
```yml
title: 'COSCUP 2017'
start: '2017-08-05T08:30'
end: '2017-08-06T17:00'
location: '臺灣大學社會科學院 / 臺北市大安區羅斯福路四段一號'
url: 'https://coscup.org/2017/'
info: '開源人年會 2017'
org:
  name: 'COSCUP'
  url: 'https://coscup.org/2017/'
```
