### ISSUE TITLE
+JSDC 2017

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#82]
```yml
title: 'JSDC 2017'
start: '2017-11-04T08:30'
end: '2017-11-05T17:00'
location: '臺灣大學社會科學院 / 臺北市大安區羅斯福路四段一號'
url: 'http://2017.jsdc.tw/'
info: 'JSDC 2017'
org:
  name: 'JSDC'
  url: 'http://jsdc.tw/'
```
