### ISSUE TITLE
+Happy CSSer - 13

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#83]
```yml
title: 'Happy CSSer - 13'
start: '2017-07-01T13:30'
end: '2017-07-01T17:30'
location: 't,mot 集界科技 / 台北市大安區羅斯福路三段283巷21弄3號 / 永樂座的「對面」'
url: 'https://www.facebook.com/events/1937048433232046/'
info: '出門玩 CSS、嘴一嘴~'
org:
  name: 'R+'
  url: 'https://www.facebook.com/rplus.tw'
```
