### ISSUE TITLE
+Facebook Developer Circle: Taipei - Meetup #3

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#85]
```yml
title: 'Facebook Developer Circle: Taipei - Meetup #3'
start: '2017-07-26T19:00'
end: '2017-07-26T22:00'
location: '105台北市松山區民權東路三段142號17樓, Taipei, Taiwan 105 / CHOCOLABS 歐酷網路'
url: 'https://www.facebook.com/events/1480273335356579/'
info: |
  KKTIX: https://fdctaipei.kktix.cc/events/fdc201707

  🎙 Keynote #1
  主題：如何在App產品中導入 Facebook Analytics & 透過 Facebook Analytics 把你的 User 看透透
  講者：Kevin Huang (CHOCOLABS)

  🎙 Keynote #2
  主題：如何透過 Event Source Group (ESG) 瀏覽全通路用戶數據
  講者：Clement Tang (91APP)

  ⚡️ Lightning Talk
  【用PyMessager加速開發chatbot on fb】by 大白

org:
  name: 'Facebook Developer Circle: Taipei'
  url: 'https://www.facebook.com/groups/DevCTaipei/'
```
