### ISSUE TITLE
+高雄前端社群#29 - 教到你嫑嫑的 React 工作坊

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#87]
```yml
title: '高雄前端社群#29 - 教到你嫑嫑的 React 工作坊'
start: '2017-08-13T09:30'
end: '2017-08-13T16:30'
location: '高雄市鹽埕區七賢三路123號3樓 / 高雄數位內容創意中心'
url: https://www.facebook.com/events/318915041867489/
info: |
  KKTIX: https://gonsakon-7655f2.kktix.cc/events/a5791ac5-f60f9c-cc9dec-eb381d-6b57e9-3a5710-61e623-17b85b-3ac7a7-8f8c6c-3a422e-e7994a-15adf0-335891

  ReactMaker - 是一群在高雄對 React JS 有興趣的人們組成的一個小小社團，目前活躍於中南部的ReactJs教學分享讀書會；我們會不定期的分享範例(Open source)在粉絲團上，志立於分享教學讓新手可以比較有效率的上手，以提升中南部前端工程師的戰力，也歡迎各位高手來分享、教學、交流。

org:
  name: '高雄前端社群'
  url: 'https://www.facebook.com/groups/358503154261390'
```
