### ISSUE TITLE
+Let Free code#1

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#88]
```yml
title: 'Let Free code#1'
start: '2017-07-13T19:00'
end: '2017-07-13T22:00'
location: '古亭和平小樹屋 - 305（106台北市大安區和平東路一段8號3樓）'
url: 'https://www.facebook.com/LetFreeCode/posts/322728148149648'
info: 'Let Free code#1'
org:
  name: 'Letfreecode'
  url: 'https://www.facebook.com/LetFreeCode/'
```
