### ISSUE TITLE
+REACTJS入門實作推廣活動(2017年7月 台北/台南)

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#89]
```yml
title: 'REACTJS入門實作推廣活動(2017年7月 台北/台南)'
start: '2017-07-09T13:00'
end: '2017-07-09T17:00'
location: '台南市永康區大武街34號2樓 (好想工作室，台南市火車大橋車站附近，康是美樓上)'
url: 'https://reactjs-tw.top/event-201707'
info: |
  本次將由Eddy講師帶領各位入門ReactJS相關技術，在4個小時的實作推廣課程中帶領你進入ReactJS的開發大門！
```
