### ISSUE TITLE
+Taipei.rb 201708：以 Vue.js 開發電子商務網站架構與眉角

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#92]
```yml
title: 'Taipei.rb 201708：以 Vue.js 開發電子商務網站架構與眉角'
start: '2017-08-22T19:00'
end: '2017-08-22T22:00'
location: '五倍紅寶石出礦坑 / 台北市中正區衡陽路七號五樓'
url: https://rubytaiwan.kktix.cc/events/taipeidotrb-201708
info: |
  講者：Mayu
  分享以 Vue.js 配合 Rails 前後端分離的大型專案開發與架構方式，使用哪一些Vue的功能與Packages介紹，以及專案當中遇到的Bugs與解決辦法。

org:
  name: 'Ruby Taiwan'
  url: 'https://www.facebook.com/ruby.taiwan/'
```
