### ISSUE TITLE
+台中前端社群 08/15 React Native Workshop - 1 @夢種子

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#95]
```yml
title: '台中前端社群 08/15 React Native Workshop - 1 @夢種子'
start: '2017-08-15T19:00'
end: '2017-08-15T21:10'
location: 'Dreamseeds 夢種子 / 西屯區河南路二段262號14F'
url: 'https://www.facebook.com/dreamseeds.org/posts/736885973170696'
info: |
  KKTIX: https://taichung-frontend.kktix.cc/events/170815-001

  本活動將自8/15(二)開始，預計10次左右，以workshop與討論的形式一步一步帶領大家使用React Native(以下簡稱RN)進行App開發，歡迎尚未踏入App開發領域的前端工程師

org:
  name: '台中前端社群'
  url: 'https://www.facebook.com/groups/taichung.f2e/'
```
