### ISSUE TITLE
Angular Taiwan 2018 海上篇

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#97]
```yml
title: 'Angular Taiwan 2018 海上篇'
start: '2018-07-03T17:00'
end: '2018-07-07T07:00'
location: '遊輪盛世公主號'
url: 'https://www.facebook.com/groups/augularjs.tw/permalink/1712635168746846/'
info: |
  KKTIX: https://angular.kktix.cc/events/522272ed

  誰說技術研討會不能帶家人朋友一起去?!

  Angular Taiwan 社群就是要您們邀請你的家人朋友，一起跟我們出去玩學習

  本次的活動地點為:  盛世公主號～沖繩、石垣

org:
  name: 'Angular User Group Taiwan'
  url: 'https://www.facebook.com/groups/augularjs.tw/'
```
