### ISSUE TITLE
Mozilla Developer Conference 2017

### ISSUE THREAD

**Issue by Rplus** [f2etw/seek-meetup#98]
```yml
title: 'Mozilla Developer Conference 2017'
start: '2017-09-22T09:00'
end: '2017-09-22T16:30'
location: '​台北威斯汀六福皇宮 B3 永樂宮'
url: 'https://www.mozilladevtw2017.com/'
info: |
  FB event: https://www.facebook.com/events/276049929466918/

  史上第一回  Mozilla開發者大會在台北 Mozilla 誠摯邀請您前來參與首次盛會！

  在這一天的活動中，您可以了解 Web 最新技術發展，更可近距離了解 Mozilla 新一代瀏覽器引擎的「量子專案」（Project Quantum）如何讓年底即將問世的新 Firefox 華麗變身。此外，您也有機會一窺 Mozilla 在 Servo、WebVR 與語音辨識等領域的無限可能。

org:
  name: 'Mozilla Taiwan'
  url: 'https://www.mozilla.org/zh-TW/'
```
